server:
  port : 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
    generate-ddl: true